openapi: 3.0.0
info:
  title: MindTickle DataDog Integrated API
  description: please add your description
  version: 1.0.0

servers:
  - url: https://130.211.38.178.nip.io

paths:
  /avgTotalResponseTime:
    get:
      summary: AvgTotalResponse
      parameters:
             - in: header
               name: Accept
               required: true
               schema:
                 type: string
               example:
                 application/json
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}
  /policyErrorMetrics:
    get:
      summary: policyErrorMetrics
      parameters:
             - in: header
               name: Accept
               required: true
               schema:
                 type: string
               example:
                 application/json
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}
  /mainmetricsdatadog:
    get:
      summary: MainDataDog
      parameters:
             - in: header
               name: Accept
               required: true
               schema:
                 type: string
               example:
                 application/json
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}
  /api/v2/series:
    post:
      summary: DatadogsSubmitMetricsAPI
      parameters:
             - in: header
               name: Accept
               required: true
               schema:
                 type: string
               example:
                 application/json
             - in: header
               name: Content-Type
               required: true
               schema:
                 type: string
               example:
                 application/json
             - in: header
               name: Content-Encoding
               required: true
               schema:
                 type: string
               example:
                 string
             - in: header
               name: DD-API-KEY
               required: true
               schema:
                 type: string
               example:
                 70405486803549b0a74e29b16c74611b
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                series:
                  type: array
                  items :
                   type : object
                   properties:
                     metric:
                       type: string
                     type:
                       type: number
                     resources:
                       type: array
                       items :
                        type : object
                        properties:
                          name:
                            type: string
                          type:
                            type: string
                     points:
                       type: array
                       items :
                        type : object
                        properties:
                          timestamp:
                            type: number
                          value:
                            type: number
            example: {
        "series": [
            {
                "metric": "apigee_avg(total_response_time)",
                "type": 2,
                "resources": [
                    {
                        "name": "shipMetrics",
                        "type": "apigee_proxy"
                    }
                ],
                "points": [
                    {
                        "timestamp": 1676450640,
                        "value": 1425.3333333333335
                    }
                ]
            }
        ]
}
      responses:
        "200":
          description: it is an example response
          content:
            JSON/application:
              schema:
                type: object
              example:
                {}